name: snagtick
services:
  backend:
    image: golang:1.23-alpine
    ports:
      - 8000:8888
  frontend:
    image: node:lts-alpine
    ports:
      - 3000:5173
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1
