INSERT INTO "events"
("image","title","date","descriptions")
VALUES
('https://w0.peakpx.com/wallpaper/363/941/HD-wallpaper-valentino-rossi-motogp-vr46.jpg','MOTOGP, Mandalika Indonesia','2024-09-27','indonesia kembali menjadi salah satu tuan rumah untuk pagelaran MotoGP pada tahun 2024. MotoGP Mandalika akan dilaksanakn di Sirkuit Pertamina Mandalika, Lombok, Indonesia'),
('https://ueeshop.ly200-cdn.com/u_file/UPAY/UPAY568/2306/11/photo/005.jpg?x-oss-process=image/quality,q_80/resize,m_lfit,h_0,w_370','Art Jakarta','2024-10-04','Art Jakarta adalah salah satu pameran seni terkemuka di Indonesia yang dinantikan oleh banyak pecinta seni. Art Jakarta diselenggarakan setiap tahun pada bulan November di JIExpo Kemayoran. Art Jakarta adalah pekan seni internasional yang secara khusus menyuarakan seni kontemporer Asia. Beberapa galeri dan seniman juga memamerkan karyanya di Art Jakarta pada tahun 2023, antara lain: Galeri Gajah, Agenda Seni, Putu Sutawijaya, Muklay, & Nyoman Masriadi.'),
('https://th.bing.com/th/id/OIP.mSj827anmtOvCWnWSSgBwgAAAA?rs=1&pid=ImgDetMain','Dieng Culture Festival','2024-09-04',' Dieng Culture Festival adalah acara kebanggaan warga Dieng yang memadukan keindahan alam dengan keunikan budaya'),
('https://static.wixstatic.com/media/0c8d52_b6d49202225e4f2998e1b5f409970e8d~mv2.jpg/v1/fill/w_407,h_610,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/0c8d52_b6d49202225e4f2998e1b5f409970e8d~mv2.jpg','JAKARTA INTERNATIONAL MARATHON 2024','2024-6-23','Jakarta International Marathon 2024 diharapkan selalu dapat menjadi wadah & inspirasi bagi sports enthusiast di Indonesia dalam menyalurkan hobi & prestasinya tentunya dengan beberapa perbaikan serta kolaborasi & dukungan dari Pemprov & PASI Indonesia demi kepercayaan serta kenyamanan peserta BTN Jakarta International Marathon (JAKIM).'),
('https://seremonia.id/wp-content/uploads/2024/06/449076256_1468509920536163_6277607344583032024_n.jpeg','Festival Payung','2024-09-06','Perpaduan antara wastra nusantara dan payung tradisi menjadi tema utama FESPIN 2024. Festival ini akan mengeksplorasi visual artistik nusantara dengan spirit kreativitas dan inovasi yang tiada henti. Tujuan utamanya adalah untuk menghidupkan kembali “Indonesian Living Heritage” – warisan tradisi yang hidup, yang siap diwariskan dari generasi ke generasi sebagai basis ekonomi kreatif dan aset wisata bagi masyarakat lokal.'),
('https://cdn.dribbble.com/users/12375035/screenshots/20498274/dribbble.jpg','PON XXI Aceh-Sumut 2024','2024-09-08','Pekan Olahraga Nasional (PON) XXI tahun 2024 digelar oleh dua provinsi sekaligus yakni Aceh dan Sumatera Utara. Rencananya gelaran olahraga nasional ini digelar 8-20 September 2024.'),
('https://live.staticflickr.com/4908/45924430384_5798c4486c.jpg','SIPA (Solo International Performing Arts)','2024-08-31','Solo International Performing Arts (SIPA) adalah perayaan tahunan ekspresi artistik, yang mempertemukan para pemain berbakat dari Indonesia dan di seluruh dunia'),
('https://thumbs.dreamstime.com/b/fim-mxgp-motocross-world-championship-grand-prix-thailand-suphanburi-march-jorge-zaragoza-honda-motorcycle-competes-68229883.jpg','Motocross Grand Prix MXGP','2024-06-30','Kejuaraan Dunia Motocross Grand Prix MXGP, merilis kalender balapannya untuk 2024. Indonesia resmi menjadi tuan rumah pada dua seri balapan musim 2024, di Nusa Tenggara Barat (NTB). Dua seri balapan motocross tersebut, akan digelar di Sumbawa (30 Juni 2024), dan Lombok (7 Juli 2024).'),
('https://i.pinimg.com/originals/4d/c4/16/4dc416184165cbe5884299eedd17ee2a.jpg','Indonesia Open 2024','2024-06-04','Indonesia Open merupakan salah satu Tur Dunia BWF paling bergengsi dan paling ditunggu. Pada tahun 202, ajang Indonesia Open akan kembali digelar di Jakarta, pada tanggal 4-9 Juni mendatang'),
('https://i.pinimg.com/474x/b2/79/ac/b279acebceac26d59b9b78ec33a7f8f2.jpg','Ultra Beach Bali','2024-06-06','Ajang Ultra Beach Bali 2024 dijadwalkan berlangsung pada tanggal 6-7 Juni 2024. Festival yang akan digelar di Café Del Mar, sebuah resort village kawasan Canggu, Bali tersebut memiliki konsep festival musik elektronik (EDM Ultra) tepi pantai.')
